### ISSUE TITLE
No notification when workflow run is triggered

### ISSUE THREAD

**Issue by IvanAlieksieienko** [integrations/microsoft-teams#384]
**Describe the bug**  
Hi there. According to the [documentation](https://github.com/integrations/microsoft-teams?tab=readme-ov-file#actions-workflow-notifications:~:text=You%20will%20get%20notified%20when%20a%20new%20workflow%20run%20is%20triggered.%20And%20you%20can%20track%20the%20live%20status%20of%20the%20jobs.) for "Actions workflow notifications":

> You will get notified when a new workflow run is triggered. And you can track the live status of the jobs.

However, this functionality does not work as described.

**Steps to Reproduce**  
1. Configure notifications using the following command:  
   `Subscribe owner/repo workflows:{name:"Test Notifications to Microsoft Teams" branch:"main" event:"workflow_dispatch"}`
2. Start the workflow manually. Here's an example workflow:
    ```yaml
    name: "Test Notifications to Microsoft Teams"
    on:
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Mock long-running job
            run: |
              echo "Starting a long-running mock job..."
              for i in {1..6}; do
                echo "Processing step $i/6"
                sleep 10  # Simulate a 10-second task for each step
              done
              echo "Long-running mock job complete."
    ```

**Expected behavior**  
A notification should be sent when the workflow starts, with additional updates as the status changes throughout the workflow execution, including when it completes.

**Actual behavior**  
We only receive a notification when the workflow finishes, with no updates during its execution.

**Screenshots**  
![image](https://github.com/user-attachments/assets/8a2ecde2-f189-4af1-93e9-3bfeed11d074)

**Additional context**  
It is essential to receive notifications when a workflow is triggered, especially in scenarios like manual deployments to the staging environment. The entire team needs to be aware that changes will occur soon. Moreover, timely notifications are crucial when a pipeline gets stuck without throwing an error.

---

Let me know if you'd like to adjust or add anything else!
