### ISSUE TITLE
Please support GitHub Actions support

### ISSUE THREAD

**Issue by mmerdes** [integrations/microsoft-teams#40]
Feedback on the state of the build would be highly appreciated,
especially notifications of failed builds.

**Comment by ashokirla** [comment]
@mmerdes Thanks for your feedback. Yes, support for GitHub Actions is in our Roadmap. We will work on it early next year.

**Comment by cdelgadob** [comment]
Hi @ashokirla , how is this progressing?

I'd like to trigger actions (using a workflow_dispatch event) with a custom parameter set, is that something you are considering as well?

Thanks

**Comment by davetapley** [comment]
I can't vouch for the code, but I just used this and it worked 👌🏻 
https://github.com/aliencube/microsoft-teams-actions

**Comment by gauravsaralMs** [comment]
@davetapley : can you share the card/ notification you are seeing on teams ?

**Comment by davetapley** [comment]
I'm sure it could be made prettier 🙈 

<img width="486" alt="Microsoft_Teams" src="https://user-images.githubusercontent.com/48232/111415827-ee3f9b00-869f-11eb-89ec-2b515bdd2d19.png">

**Comment by bvxzee** [comment]
Do we have any updates on this? Apparently, we cannot use non github certified actions

**Comment by eerkunt** [comment]
Any hope this can be implemented somewhere soon ? 🙏

**Comment by cquanu** [comment]
+1

**Comment by daidnoggin** [comment]
Here is a job that can post to MS Teams if a build has failed, without using external code. Something to use until this feature is done.

```yaml
  post-build-failures:
    name: Post failures to MS Teams
    runs-on: ubuntu-latest
    needs: [build, test]
    if: failure() && github.event_name == 'push'
    steps:
      - name: Generate variables
        run: |
          echo '${{ toJSON(needs) }}' > /tmp/needs.json
          echo 'FAILEDJOBS='$(cat /tmp/needs.json | jq 'path(.[] | select(.result=="failure"))' | jq -rs 'flatten | join(", ")') >> $GITHUB_ENV
          
          echo 'MSG<<EOF' >> $GITHUB_ENV
          echo 'Author: ${{ github.event.head_commit.author.name }}\n\nCommit: ${{ github.event.head_commit.message }}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Post WebHook to MS Teams
        run: |
          curl -X POST <Incoming Webhook URL> -d '{
            "@context": "https://schema.org/extensions",
            "@type": "MessageCard",
            "themeColor": "A1051D",
            "title": "${{ env.FAILEDJOBS }} step has failed",
            "text": "${{ env.MSG }}\n\nClick **View Details** to learn more",
            "potentialAction": [
              {
                "@type": "OpenUri",
                "name": "View Details",
                "targets": [
                  { "os": "default", "uri": "https://github.com/<User>/<Repository>/actions/runs/${{ github.run_id }}" }
                ]
              }
            ]
          }'
```



![image](https://user-images.githubusercontent.com/4187453/121008203-17228880-c7d6-11eb-88a1-b49dd30d1840.png)
